apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: slurm-prority
value: 100
globalDefault: false
description: "This priority class should be used for slurm pods. Used to preempt lower priority workloads."