kind: ServiceAccount
apiVersion: v1
metadata:
  name: slurm-{{ .Values.namespace }}-sa
---
# We want pods to be able to get node labels from the node they are running on,
# in particular the nodepool label
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slurm-{{ .Values.namespace }}-get-node-labels
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "update", "patch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: slurm-{{ .Values.namespace }}-get-node-labels-crb
subjects:
  - kind: ServiceAccount
    name: slurm-{{ .Values.namespace }}-sa
    namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: slurm-{{ .Values.namespace }}-get-node-labels
---
# We want slurm's RebootProgram to delete the pod, so it pulls in any spec
# changes on the StatefulSet. We also want to get pods so we can get their GKE
# node hostnames.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-access
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete", "deletecollection", "get", "list", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-access-rb
subjects:
- kind: ServiceAccount
  name: slurm-{{ .Values.namespace }}-sa
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-access
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slurm-{{ .Values.namespace }}-slonklet
rules:
- apiGroups:
  - slonk.your-org.com
  resources:
  - physicalnodes
  - slurmjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - slonk.your-org.com
  resources:
  - physicalnodes/finalizers
  - slurmjobs/finalizers
  verbs:
  - update
- apiGroups:
  - slonk.your-org.com
  resources:
  - physicalnodes/status
  - slurmjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: slurm-{{ .Values.namespace }}-slonklet-crb
subjects:
- kind: ServiceAccount
  name: slurm-{{ .Values.namespace }}-sa
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: slurm-{{ .Values.namespace }}-slonklet
