# permissions for end users to edit physicalnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: physicalnode-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: slonklet
    app.kubernetes.io/part-of: slonklet
    app.kubernetes.io/managed-by: kustomize
  name: physicalnode-editor-role
rules:
- apiGroups:
  - slonk.your-org.com  # TODO: Replace with your organization domain
  resources:
  - physicalnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - slonk.your-org.com  # TODO: Replace with your organization domain
  resources:
  - physicalnodes/status
  verbs:
  - get
